version: 2
project_name: fotos-mcp

builds:
  - builder: rust
    id: fotos-mcp
    binary: fotos-mcp
    # Build from the src-mcp workspace member
    dir: src-mcp
    targets:
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
      - x86_64-apple-darwin
      - aarch64-apple-darwin
      - x86_64-pc-windows-msvc
    flags:
      - --release
      - --locked
    env:
      - CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

brews:
  - name: fotos-mcp
    repository:
      owner: charly-vibes
      name: homebrew-charly
      branch: main
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: "https://github.com/charly-vibes/fotos"
    description: "MCP server for Fotos — AI-powered screenshot tool"
    license: "MIT"
    test: |
      system "#{bin}/fotos-mcp", "--version"

scoops:
  - name: fotos-mcp
    repository:
      owner: charly-vibes
      name: scoop-charly
      branch: main
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    folder: bucket
    homepage: "https://github.com/charly-vibes/fotos"
    description: "MCP server for Fotos — AI-powered screenshot tool"
    license: "MIT"

release:
  github:
    owner: charly-vibes
    name: fotos
  prerelease: auto
  name_template: "fotos-mcp {{ .Tag }}"

changelog:
  use: github
  sort: asc
  filters:
    exclude: ['^docs:', '^chore:', '^style:', '^test:', '^refactor:']
